config/routes.rb
Rails.application.routes.draw do
  resources :articles
  root 'pages#home'
  get 'about', to: 'pages#about'
  get 'signup', to: 'users#new'
  resources :users, except: [:new]
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :user
  validates :title, presence: true, length: { minimum: 8, maximum: 100 }
  validates :description, presence: true, length: { minimum: 10, maximum: 300 }
end

app/models/user.rb
class User < ApplicationRecord
  before_save { self.email = email.downcase }
  has_many :articles
  validates :username, presence: true, 
                      uniqueness: { case_sensitive: false }, 
                      length: { minimum: 3, maximum: 25 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, 
                    uniqueness: { case_sensitive: false }, 
                    length: { maximum: 105 },
                    format: { with: VALID_EMAIL_REGEX }
  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    def home
        
    end

    def about
    end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: %i[ show edit update destroy ]

  # GET /articles or /articles.json
  # def index
  #   @articles = Article.all
  # end

  # GET /articles/1 or /articles/1.json
  def show
  end

  def index
    @articles = Article.all
  end

  def new
    @article = Article.new
  end

  def edit
  end

  def create
    @article = Article.new(article_params)
    @article.user = User.first
    if @article.save
      flash[:notice] = "Article was created successfully."
      redirect_to @article
    else
      render 'new', status: :unprocessable_entity 
    end
  end

  def update
    if @article.update(article_params)
      flash[:notice] = "Article was updated successfully."
      redirect_to @article
    else
      render 'edit', status: :unprocessable_entity 
    end
  end

  def destroy
    @article.destroy
    redirect_to articles_path
  end

  private

  def set_article
    @article = Article.find(params[:id])
  end

  def article_params
    params.require(:article).permit(:title, :description)
  end
  # GET /articles/new
  # def new
  #   @article = Article.new
  # end

  # GET /articles/1/edit
  # def edit
  # end

  # POST /articles or /articles.json
  # def create
  #   @article = Article.new(article_params)

  #   respond_to do |format|
  #     if @article.save
  #       format.html { redirect_to article_url(@article), notice: "Article was successfully created." }
  #       format.json { render :show, status: :created, location: @article }
  #     else
  #       format.html { render :new, status: :unprocessable_entity }
  #       format.json { render json: @article.errors, status: :unprocessable_entity }
  #     end
  #   end
  # end

  # PATCH/PUT /articles/1 or /articles/1.json
  # def update
  #   respond_to do |format|
  #     if @article.update(article_params)
  #       format.html { redirect_to article_url(@article), notice: "Article was successfully updated." }
  #       format.json { render :show, status: :ok, location: @article }
  #     else
  #       format.html { render :edit, status: :unprocessable_entity }
  #       format.json { render json: @article.errors, status: :unprocessable_entity }
  #     end
  #   end
  # end

  # DELETE /articles/1 or /articles/1.json
  # def destroy
  #   @article.destroy

  #   respond_to do |format|
  #     format.html { redirect_to articles_url, notice: "Article was successfully destroyed." }
  #     format.json { head :no_content }
  #   end
  # end

  # private
  #   # Use callbacks to share common setup or constraints between actions.
  #   def set_article
  #     @article = Article.find(params[:id])
  #   end

  #   # Only allow a list of trusted parameters through.
  #   def article_params
  #     params.require(:article).permit(:title, :description)
  #   end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email:params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      flash[:notice] = 'Logged successfully'
      redirect_to user
    else
      flash.now[:alert] = 'There was something wrong with your login details!'w
      render 'new', status: :unprocessable_entity
    end
  end

  def destroy
    session[:user_id] = nil
      flash[:notice] = 'Logged out'
      redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def show
    @user = User.find(params[:id])
  end

  def index
    @users = User.all
  end

  def edit
    @user = User.find(params[:id])
  end

  def create
    @user = User.new(user_params)
    if @user.save
      flash[:notice] = "Welcome to our blog #{@user.username}, you have successfully signed up!"
      redirect_to users_path
    else
      render 'new', status: :unprocessable_entity 
    end
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:notice] = "Account was updated successfully."
      redirect_to users_path
    else
      render 'edit', status: :unprocessable_entity 
    end
  end

  private

  def user_params
    params.require(:user).permit(:username, :email, :password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/articles/_form.html.erb
<% if @article.errors.any? %>
  <h2>The following errors prevented the article from being saved</h2>
  <ul>
    <% @article.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
  </ul>
<% end %>

<%= form_with(model: @article, local: true) do |f| %>
  <p> 
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </p>

  <p> 
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </p>

  <p>
    <%= f.submit %>
  </p>
  <% end %>

app/views/articles/create.html.erb
<h1></h1>

app/views/articles/edit.html.erb
<h1>Edit Article</h1>

<%= render 'form' %>

<%= link_to 'Cancel edit and return to articles\' listing', articles_path(@article) %>

app/views/articles/index.html.erb
<h1>Articles listing page</h1>

<table>
  <thead>
    <tr>
      <th>Author</th>
      <th>Title</th>
      <th>Description</th>
      <th colspan="3">Actions</th>
    </tr>
  </thead>
  <tbody>
  <% @articles.each do |article| %>
      <tr>
      <td><%= article.user.username %></td>
        <td><%= article.title %></td>
        <td><%= article.description %></td>
        <td><%= link_to 'Show', article_path(article) %></td>
        <td><%= link_to 'Edit', edit_article_path(article), method: :edit %></td>
        <td><%= button_to 'Delete', article_path(article), method: :delete, form: { data: { turbo_confirm: "Are you sure you want to delete this article?" }} %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<p><%= link_to 'Create new article', new_article_path %></p>
<%= link_to 'Return to bloggers\' listing', users_path(@user) %>

<%= link_to 'Home', root_path %>

app/views/articles/new.html.erb
<h1>Create a new Article</h1>

<%= render 'form' %>

<%= link_to 'Return to articles\' listing', articles_path(@article) %>

<%= link_to 'Home', root_path %>

app/views/articles/show.html.erb
<h1>Showing article details</h1>

<p><strong>Author: </strong><%= @article.user.username %></p>
<p><strong>Title: </strong><%= @article.title %></p>
<p><strong>Description: </strong><%= @article.description %></p>

<%= link_to 'Edit', edit_article_path(@article) %>
<%= button_to 'Delete', article_path(@article), method: :delete, form: { data: { turbo_confirm: "Are you sure you want to delete this article?" }} %>
<%= link_to 'Return to articles\' listing', articles_path(@article) %>
<%= link_to 'Home', root_path %>

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
    <%= msg %>
  <% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MyNewApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
  <%= render 'layouts/messages' %>
    <%= yield %>
  </body>
</html>

app/views/pages/about.html.erb
<h1>This is an about page</h1>

<%= link_to 'Articles\' listing', articles_path(@article) %>
<%= link_to 'Home', root_path %>

app/views/pages/home.html.erb
<h1>This is a home page</h1>

<%= link_to 'Articles\' listing', articles_path(@article) %> |
<%= link_to 'Return to bloggers\' listing', users_path(@user) %>
<%= link_to 'About', about_path %>

app/views/users/_form.html.erb
<% if @user.errors.any? %>
  <h2>The following errors prevented the user from being saved</h2>
  <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
  </ul>
<% end %>

<%= form_with(model: @user, local: true) do |f| %>
  <p> 
    <%= f.label :username %><br />
    <%= f.text_field :username %>
  </p>

  <p> 
    <%= f.label :email %><br />
    <%= f.email_field :email %>
  </p>

  <p> 
    <%= f.label :password %><br />
    <%= f.password_field :password %>
  </p>

  <p>
    <%= f.submit(@user.new_record? ? 'Sign up' : 'Update account') %>
  </p>
  <% end %>

app/views/users/edit.html.erb
<h1>Edit your profile</h1>

<%= render 'form' %>

<%= link_to 'Return to articles\' listing', articles_path(@article) %>

<%= link_to 'Home', root_path %>

app/views/users/index.html.erb
<h1>Our Bloggers</h1>

<% @users.each do |user| %>
  <div><%= user.username %></div>
  <div><%= link_to 'Show', user_path(user) %></div>
  <div><%= link_to 'Edit', edit_user_path(user), method: :edit %></div>
  <div><%= button_to 'Delete', user_path(user), method: :delete, form: { data: { turbo_confirm: "Are you sure you want to delete this article?" }} %></div>
<% end %>

app/views/users/new.html.erb
<h1>Signup a new User</h1>

<%= render 'form' %>

<%= link_to 'Return to articles\' listing', articles_path(@article) %>

<%= link_to 'Home', root_path %>

app/views/users/show.html.erb
<h1><%= @user.username %>'s Profile</h1>

<%= link_to 'Return to bloggers\' listing', users_path(@user) %>
<%= link_to 'Edit your profile', edit_user_path(@user) %>
<%= link_to 'Home', root_path %>